runtime: python
env: flex
runtime_config:
    python_version: 3.6
entrypoint: gunicorn -b :$PORT main:app --timeout 300

resources:
  memory_gb: 12
  cpu: 2
  disk_size_gb: 30

readiness_check:
  app_start_timeout_sec: 6000

manual_scaling:
  instances: 2